// LOGIN
export const LOGIN_UPDATE_FIELD = "LOGIN_UPDATE_FIELD";
export const LOGIN_SET_ERRORS = "LOGIN_SET_ERRORS";
export const LOGIN_CLEAR_ERRORS = "LOGIN_CLEAR_ERRORS";

export const LOGIN_SUBMIT_REQUEST = "LOGIN_SUBMIT_REQUEST";
export const LOGIN_SUBMIT_SUCCESS = "LOGIN_SUBMIT_SUCCESS";
export const LOGIN_SUBMIT_FAILURE = "LOGIN_SUBMIT_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Exercises
export const FETCH_EXERCISES_REQUEST = "FETCH_EXERCISES_REQUEST";
export const FETCH_EXERCISES_SUCCESS = "FETCH_EXERCISES_SUCCESS";
export const FETCH_EXERCISES_FAILURE = "FETCH_EXERCISES_FAILURE";

// Workout Selection
export const RESET_PICKER = "RESET_PICKER";
export const SELECT_MUSCLE_GROUP = "SELECT_MUSCLE_GROUP";
export const SELECT_EXERCISE = "SELECT_EXERCISE";
export const RESET_WORKOUT_SELECTION = "RESET_WORKOUT_SELECTION";
export const SET_CURRENT_WORKOUT = "SET_CURRENT_WORKOUT";
export const ADD_EXERCISE_BLOCK = "ADD_EXERCISE_BLOCK";
export const UPDATE_EXERCISE_SET = "UPDATE_EXERCISE_SET";
export const ADD_SET_TO_EXERCISE = "ADD_SET_TO_EXERCISE";
export const REMOVE_SET_FROM_EXERCISE = "REMOVE_SET_FROM_EXERCISE";
export const REMOVE_EXERCISE_BLOCK = "REMOVE_EXERCISE_BLOCK";
export const SET_WORKOUT_STATUS = "SET_WORKOUT_STATUS";
